#Let’s use what we’ve learned so far to create a lottery number generator. Before we can build it, we need to determine precisely 
#how it will work. We have decided that we want to generate ten numbers, each ranging from 1 to 50. Let’s create a function that 
#can do that.

from random import randint


def lottery_generator():
    numbers = []
    for number in range(0, 10):
        numbers.append(randint(1, 50))
    return numbers

print("This weeks winning lottery numbers are %s" % lottery_generator())

# OUTPUT:
# Python 3.6.1 (default, Dec 2015, 13:05:11)
# [GCC 4.8.2] on linux
   
# This weeks winning lottery numbers are [23, 39, 13, 24, 40, 19, 27, 36, 46, 15]
   
# NOTES:
# Here we import the randint function. Then we define a new function called lottery_generator. Inside the lottery_generator 
# function, we create an empty list called numbers. After that, we create a for loop a with a range of 
# 0 to 10. For each iteration of the loop, we create a new item in the numbers list by using the append 
# method. The append method will append a new item to the end of the list, and that new item is a randomly 
# generated int from a range between 1 and 50. Once we’ve iterated over the sequence generated by range, 
# we just return the list. Then we print out a message that tells the user what the numbers were for 
# that week’s lottery.